### PR TITLE
Feature/user posters

### PR DESCRIPTION
**Pull request by keiranmraine**
@denis-yuen, following our discussion about posters I've made some minor edits and added my entry.

### CODE REVIEW

**Comment by denis-yuen** [comment]
@garyluu could you do a build and see whether the relative path survives `ng build`? 
If not, just change it to an absolute path and then accept the pull request. Thanks!

**Comment by garyluu** [comment]
The first two links are broken on the UI build.  Looks like it may only work on GitHub, but not the site.  In its place, we currently have a table of contents which direct to the same place as those two links.

**Comment by denis-yuen** [comment]
@garyluu  Oh one quick note. Keep in mind that linking either to the GitHub copy of the poster or having a copy on our website is fine.

**Comment by denis-yuen** [comment]
thanks @keiranmraine !

**Pull request merged**
