### PR TITLE
Feature/deregister

### PR DESCRIPTION
**Pull request by k-cao**
Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic compilation and unit tests by running `grunt`

### CODE REVIEW

**Comment by denis-yuen** [comment]
@k-cao remind me to try this out after stand-up tommorow

**Comment by k-cao** [comment]
- fixed broken video
- added unit tests for buttons
- remove extra li

**Comment by denis-yuen** [comment]
@k-cao  FYI , merge conflict

**Comment by k-cao** [comment]
Fixed previous merge conflict

**Comment by denis-yuen** [comment]
Same here, I think this is ready for the demo today.

**Comment by denis-yuen** [comment]
Reminder from demo:  use the standard angular pop-up for this

**Pull request closed without merging**
